baseURL = 'http://mysite/'
languageCode = 'en-gb'
title = 'eLearningWorld Example Hugo Site'
theme = "elw"
enableRobotsTXT = true

[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
    [menu.main.params]
        icon = "fa-solid fa-house"

[[menu.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
    [menu.main.params]
        icon = "fa-solid fa-newspaper"

[[menu.main]]
    name = 'Terms'
    pageRef = '/tags'
    weight = 30
    [menu.main.params]
        icon = "fa-solid fa-tags"

[[menu.icon]]
    url = "https://github.com/gjb2048/"
    name = "Github"
    weight = 1
    [menu.icon.params]
        icon = "fa-brands fa-github"

[[menu.icon]]
    url = "https://twitter.com/gjbarnard/"
    name = "X"
    weight = 2
    [menu.icon.params]
        icon = "fa-brands fa-x-twitter"

[[menu.icon]]
    url = "https://www.elearningworld.org/author/gbarnard/"
    name = "eLearningWorld"
    weight = 3
    [menu.icon.params]
        icon = "fa-solid fa-pen-to-square"