name = 'eLearningWorld Hugo Theme'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Hugo Theme for eLearningWorld posts'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/owner/repo'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['eLearningWorld', 'Hugo']
features = ['minimal', 'learning']

# If the theme has a single author
[author]
  name = 'Gareth Barnard'
  homepage = 'https://gjbarnard.co.uk'
